<?php

/**
* Implements hook_library_info_alter().
*/
function xb_vite_library_info_alter(&$libraries, $extension) {
  $base = [
    'attributes' => ['type' => 'module'],
    // Disabling preprocessing ensures these files are not aggregated, which
    // avoids the need for clearing Drupal caches during `npm run drupaldev`.
    'preprocess' => FALSE,
  ];

  $vite_server_origin = getenv('VITE_SERVER_ORIGIN') ?: 'http://localhost:5173';

  $libraries['xb-ui']['drupalSettings']['xb_vite'] = [
    'serverOrigin' => $vite_server_origin
  ];

  // @see https://vitejs.dev/guide/backend-integration.html
  $libraries['xb-ui']['js'] = [
    'modules/xb_vite/window.js' => $base,
    $vite_server_origin . '/@vite/client' => ['type' => 'external'] + $base,
    $vite_server_origin . '/src/main.tsx' => ['type' => 'external'] + $base,
  ];
  $libraries['xb-ui']['css'] = [];
}
