<?php

declare(strict_types=1);

use Drupal\Core\Access\AccessResult;
use Drupal\Core\Access\AccessResultInterface;
use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Session\AccountInterface;

/**
 * Implements hook_ENTITY_TYPE_access().
 *
 * Denies view access to xb_page entity with id 1.
 */
function xb_test_access_xb_page_access(EntityInterface $entity, string $operation, AccountInterface $account): AccessResultInterface {
  $cacheContexts = \Drupal::keyValue('xb_test_access')->get('cache_contexts', []);
  $cacheTags = \Drupal::keyValue('xb_test_access')->get('cache_tags', []);

  if ((int) $entity->id() === 1 && $operation === 'view') {
    return AccessResult::forbidden();
  }
  if ((int) $entity->id() === 1 && $operation === 'update' && !empty($cacheTags) && !empty($cacheContexts)) {
    return AccessResult::allowed()->addCacheContexts($cacheContexts)->addCacheTags($cacheTags);
  }

  return AccessResult::neutral();
}
