name: civictheme_canvas_demo
type: Configuration
description: Imports AI/Canvas key configuration for the local environment.
recipes:
  - core/recipes/image_media_type
install:
  - gin
  - civictheme_xb
  - ai
  - ai_agents
  - ai_provider_openai
  - canvas
  - canvas_ai
config:
  strict: false
  actions:
    ai.settings:
      simpleConfigUpdate:
        default_providers:
          embeddings:
            provider_id: openai
            model_id: text-embedding-3-small
