name: civictheme_canvas_demo
type: Configuration
description: Imports AI/Canvas key configuration for the local environment.
recipes:
  - core/recipes/image_media_type
  - civictheme_xb_demo_media
install:
  - civictheme_xb
  - ai
  - ai_agents
  - ai_provider_openai
  - canvas_ai
  - key
config:
  strict: false
  actions:
    system.theme:
      simpleConfigUpdate:
        default: civictheme_xb
        admin: gin
    ai.settings:
      simpleConfigUpdate:
        default_providers:
          embeddings:
            provider_id: openai
            model_id: text-embedding-3-small
