name: civictheme_canvas_demo
type: Configuration
description: Imports AI/Canvas key configuration for the local environment.
recipes:
  - core/recipes/image_media_type
  - canvas_media_search
config:
  strict: false
  actions:
    system.theme:
      simpleConfigUpdate:
        default: civictheme_xb
        admin: gin
    ai.settings:
      simpleConfigUpdate:
        default_providers:
          embeddings:
            provider_id: openai
            model_id: text-embedding-3-small
