name: Canvas Demo
type: Demo
description: A demonstration of Drupal Canvas.
recipes:
  - core/recipes/administrator_role
  - core/recipes/core_recommended_maintenance
  - core/recipes/core_recommended_performance
  - drupal_cms_admin_ui
  - drupal_cms_anti_spam
  - drupal_cms_authentication
  - drupal_cms_page
  - drupal_cms_privacy_basic
  - starshot_demo_blocks
install:
  - block
  - metatag
  - webform
  - canvas
  - canvas_stark
  - gin
  - starshot_demo
  - automated_cron
  - dashboard
  - eca_base
  - eca_config
  - eca_content
  - eca_misc
  - eca_render
  - eca_user
  - menu_link_content
  # The rest of these are in Standard.
  - inline_form_errors
  - config
  - menu_ui
  - token
  - views_ui
config:
  strict: false
  import:
    canvas: '*'
    image:
      - image.style.large
      - image.style.thumbnail
    starshot_demo: '*'
    metatag: '*'
    webform: '*'
    user:
      # This view mode is only needed because Olivero expects it to exist
      # in certain situations.
      - core.entity_view_mode.user.compact
      - views.view.user_admin_people
  actions:
    # Disable all components XB generated during installation.
    canvas.component.sdc.canvas.*:
      disable: []
    gin.settings:
      simpleConfigUpdate:
        secondary_toolbar_frontend: false
    system.performance:
      simpleConfigUpdate:
        css.preprocess: false
        js.preprocess: false
    system.site:
      simpleConfigUpdate:
        page.front: '/page/1'
    system.theme:
      simpleConfigUpdate:
        default: starshot_demo
        admin: gin
    user.role.content_editor:
      grantPermissionsForEachMediaType:
        - 'create %bundle media'
        - 'delete any %bundle media'
        - 'edit any %bundle media'
      grantPermissions:
        - 'access administration pages'
        - 'access contextual links'
        - 'access media overview'
        - 'access navigation'
        - 'administer url aliases'
        - 'create url aliases'
        - 'view own unpublished media'
        - 'delete own files'
        - 'revert all revisions'
        - 'view all revisions'
        - 'view the administration theme'
    node.settings:
      simpleConfigUpdate:
        use_admin_theme: true
    user.role.authenticated:
      grantPermissions:
        - 'delete own files'
        - 'view own unpublished content'
        - 'view welcome dashboard'
    user.settings:
      simpleConfigUpdate:
        verify_mail: true
        register: admin_only
        cancel_method: user_cancel_block
    announcements_feed.settings:
      simpleConfigUpdate:
        limit: 2
    core.menu.static_menu_link_overrides:
      simpleConfigUpdate:
        definitions.announcements_feed__announcement:
          menu_name: admin
          parent: system.admin
          weight: 0
          expanded: false
          enabled: false
