services:
  pgvector:
    container_name: ddev-${DDEV_SITENAME}-pgvector
    image: pgvector/pgvector:pg16
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: db
      POSTGRES_PASSWORD: db
    restart: always
    volumes:
      - ./docker/vector_db/init/:/docker-entrypoint-initdb.d/
    labels:
      com.ddev.site-name: ${DDEV_SITENAME}
      com.ddev.approot: ${DDEV_APPROOT}
